### ISSUE TITLE
no aparece el archivo

### ISSUE THREAD

**Issue by kyory** [Glowtranslations/LordOfMagnaMaidenHeavenESP#1]
buenas tardes 
miproblema es que al completar todos los pasos en la carpeta q se crea no aparece ningun archivo aparece como  carpeta vacia me podrian decir q hago en esta situacion??

**Comment by Darkmet98** [comment]
Dime la región, método y sistema operativo que estas usando.

**Comment by Darkmet98** [comment]
También prueba a instalar net framework 4
https://www.microsoft.com/es-es/download/details.aspx?id=17851

**Comment by Darkmet98** [comment]
Han pasado 11 días y no has comentado nada más, procedo a cerrar la issue.
